version: '3.8'
services:
  dev:
    container_name: cryptocase_api_dev
    image: cryptocase-api-dev:1.0.0
    build:
        context: .
        target: development
        dockerfile: ./Dockerfile
    command: npm run start:dev
    # network_mode: host
    ports:
        - "8000:8000"
        # - 8001:8001
    networks:
        - cryptocase-backend-network
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
    restart: unless-stopped
    # environment:
    #     MONGO_USER: root
    #     MONGO_PASSWORD: root
    #     MONGO_HOSTNAME: mongodb
    #     MONGO_PORT: 27017
    #     PORT: 8000
    # depends_on:
    #     - mongo
    # links:
    #     - mongo
    # prod:
    #     container_name: cryptocase_api_prod
    #     image: cryptocase-api-prod:1.0.0
    #     build:
    #         context: .
    #         target: production
    #         dockerfile: ./Dockerfile
    #     command: npm run start:prod
    #     ports:
    #         - 3000:3000
    #         - 9229:9229
    #     networks:
    #         - cryptocase-backend-network
    #     volumes:
    #         - .:/usr/src/app
    #         - /usr/src/app/node_modules
    #     restart: unless-stopped
  mongodb:
    image : mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    restart: always
    networks:
        - cryptocase-backend-network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

networks:
  cryptocase-backend-network:
    driver: bridge